### ISSUE TITLE
 Cannot read property 'slugify' of undefined

### ISSUE THREAD

**Issue by kristianmandrup** [hparra/generator-gulp-plugin#26]
```sh
0:17 $ yo gulp-plugin
(!) this.readFileAsString() is deprecated. Use require("html-wiring").readFileAsString() instead.
(!) #_ is deprecated. Require your own version of Lodash or underscore.string
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'slugify' of undefined
    at extractPluginName (/Users/kristianmandrup/npm/lib/node_modules/generator-gulp-plugin/app/index.js:24:17)
    at GulpPluginGenerator.askFor (/Users/kristianmandrup/npm/lib/node_modules/generator-gulp-plugin/app/index.js:59:19)
    at /Users/kristianmandrup/npm/lib/node_modules/generator-gulp-plugin/node_modules/yeoman-generator/lib/base.js:429:16
    at processImmediate [as _immediateCallback] (timers.js:371:17)
```

**Comment by Tankpt** [comment]
I have encountered the same problem in node v 0.12.0.

**Comment by doug-wade** [comment]
I also repro this

```
doug-UX301LAA workplace/gulp-a11y » yo --version  
1.5.1
doug-UX301LAA workplace/gulp-a11y » node -v
v5.3.0
doug-UX301LAA workplace/gulp-a11y » npm show generator-gulp-plugin
 
{ name: 'generator-gulp-plugin',
  description: 'A Yeoman generator for gulp plugins',
  'dist-tags': { latest: '0.4.3' },
  versions: [ '0.1.0', '0.2.0', '0.3.0', '0.3.1', '0.4.0', '0.4.1', '0.4.3' ],
  maintainers: [ 'hparra <hector@hectorparra.com>' ],
  time: 
   { modified: '2014-02-17T08:03:54.838Z',
     created: '2013-12-03T12:49:09.659Z',
     '0.1.0': '2013-12-03T12:49:11.002Z',
     '0.2.0': '2013-12-04T10:16:37.870Z',
     '0.3.0': '2013-12-22T00:06:27.460Z',
     '0.3.1': '2013-12-24T06:01:12.741Z',
     '0.4.0': '2014-01-15T09:57:13.962Z',
     '0.4.1': '2014-01-16T21:00:35.368Z',
     '0.4.3': '2014-02-17T08:03:54.838Z' },
  author: 'Hector Guillermo Parra Alvarez <hector@hectorparra.com> (https://github.com/hparra)',
  repository: 
   { type: 'git',
     url: 'git://github.com/hparra/generator-gulp-plugin.git' },
  readmeFilename: 'README.md',
  version: '0.4.3',
  keywords: [ 'gulp', 'gulpfriendly', 'yeoman-generator' ],
  homepage: 'https://github.com/hparra/generator-gulp-plugin',
  bugs: 'https://github.com/hparra/generator-gulp-plugin/issues',
  main: 'app/index.js',
  scripts: { test: 'mocha' },
  dependencies: { 'yeoman-generator': '>=0.14.0', github: '>=0.1.12' },
  devDependencies: 
   { mocha: '>=1.14.0',
     github: '>=0.1.12',
     gulp: '>=3.3.0',
     'gulp-jshint': '>=1.3.4' },
  peerDependencies: { yo: '>=1.0.0' },
  engines: { node: '>=0.8.0', npm: '>=1.2.10' },
  licenses: [ { type: 'MIT' } ],
  dist: 
   { shasum: 'e39df6208ffb418ee9db55acb75395054042c216',
     tarball: 'http://registry.npmjs.org/generator-gulp-plugin/-/generator-gulp-plugin-0.4.3.tgz' },
  directories: {} }

doug-UX301LAA workplace/gulp-a11y » yo gulp-plugin                
(!) require('yeoman-generator').generators.Base is deprecated. Use require('yeoman-generator').Base directly
(!) require('yeoman-generator').generators.Base is deprecated. Use require('yeoman-generator').Base directly
(!) this.readFileAsString() is deprecated. Use require("html-wiring").readFileAsString() instead.
(!) #_ is deprecated. Require your own version of Lodash or underscore.string
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'slugify' of undefined
    at extractPluginName (/usr/local/lib/node_modules/generator-gulp-plugin/app/index.js:24:17)
    at GulpPluginGenerator.askFor (/usr/local/lib/node_modules/generator-gulp-plugin/app/index.js:59:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-gulp-plugin/node_modules/yeoman-generator/lib/base.js:436:25)
    at /usr/local/lib/node_modules/generator-gulp-plugin/node_modules/run-async/index.js:33:25
    at /usr/local/lib/node_modules/generator-gulp-plugin/node_modules/yeoman-generator/lib/base.js:446:8
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by doug-wade** [comment]
The issue comes from the use of the [deprecated built-in lodash instance](https://github.com/yeoman/generator/issues/766) -- it's being referenced at [ll 59 of index.js](https://github.com/hparra/generator-gulp-plugin/blob/d21b153772752e98d3eaa4f9efe92eb1e5bf8fa5/app/index.js#L59)
